// Nümunə elanlar — "Nümunə elanlar yüklə" düyməsi ilə bir dəfəlik doldurulur.
// Real Pexels şəkilləri istifadə olunur (pulsuz, lisenziyalı stok fotolar).
export const sampleProperties = [
  {
    title: 'Yeni Yasamal, 3 otaqlı',
    district: 'Yasamal',
    address: 'İnşaatçılar metrosu yaxınlığı',
    rooms: '3',
    area: '165',
    floor: '12',
    floorTotal: '16',
    documentType: 'çıxarış',
    dealType: 'satış',
    mortgage: true,
    price: '275000',
    description: 'Təmirli, geniş balkonlu, yeni tikili binada mənzil. Metroya piyada məsafədə.',
    images: [
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1358900/pexels-photo-1358900.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    featured: true,
    status: 'aktiv',
  },
  {
    title: 'Xətai r., Gəncə prospekti, 2 otaqlı',
    district: 'Xətai',
    address: 'Gəncə prospekti',
    rooms: '2',
    area: '85',
    floor: '4',
    floorTotal: '9',
    documentType: 'çıxarış',
    dealType: 'kirayə',
    mortgage: false,
    price: '650',
    description: 'Orta təmirli, məişət texnikası ilə. Uzunmüddətli kirayə üçün əlverişlidir.',
    images: ['https://images.pexels.com/photos/1571471/pexels-photo-1571471.jpeg?auto=compress&cs=tinysrgb&w=1200'],
    featured: false,
    status: 'aktiv',
  },
  {
    title: 'Nərimanov m., 5 otaqlı həyət evi',
    district: 'Nərimanov',
    address: 'Nərimanov metrosu yaxınlığı',
    rooms: '5',
    area: '181',
    floor: '16',
    floorTotal: '14',
    documentType: 'çıxarış',
    dealType: 'satış',
    mortgage: true,
    price: '416300',
    description: 'Panoramlı mənzərə, iki hamam otağı, geniş mətbəx. Ailə üçün ideal seçim.',
    images: ['https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1200'],
    featured: true,
    status: 'aktiv',
  },
  {
    title: 'Əhmədli metrosu, 3 otaqlı',
    district: 'Əhmədli',
    address: 'Əhmədli metrosu qarşısı',
    rooms: '3',
    area: '100',
    floor: '3',
    floorTotal: '16',
    documentType: 'çıxarış',
    dealType: 'satış',
    mortgage: false,
    price: '240000',
    description: 'Günəşli tərəf, yeni santexnika, kombi isitmə sistemi.',
    images: ['https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1200'],
    featured: false,
    status: 'aktiv',
  },
  {
    title: 'Yeni Günəşli, 2 otaqlı',
    district: 'Günəşli',
    address: 'Yeni Günəşli qəsəbəsi',
    rooms: '2',
    area: '60',
    floor: '14',
    floorTotal: '14',
    documentType: 'qanuni',
    dealType: 'kirayə',
    mortgage: false,
    price: '450',
    description: 'Tam təmirli, mebelli. Ailəyə və ya tələbələrə kirayə verilir.',
    images: ['https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=1200'],
    featured: false,
    status: 'aktiv',
  },
]
